package com.hbase;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * GenCheGuanLianService service = new GenCheGuanLianService();
 * GenCheGuanLianDelegate portType = service.getGenCheGuanLianPort();
 * portType.queryByTimeAndChepaiAndKkbhs(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "GenCheGuanLianService", targetNamespace = "http://hbase.com/", wsdlLocation = "http://10.235.34.82:8085/HbaseJPService/GenCheGuanLianPort?wsdl")
public class GenCheGuanLianService extends Service {

	private final static URL GENCHEGUANLIANSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.hbase.GenCheGuanLianService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.hbase.GenCheGuanLianService.class.getResource(".");
			url = new URL(baseUrl,
					"http://10.235.34.82:8085/HbaseJPService/GenCheGuanLianPort?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://10.235.34.82:8085/HbaseJPService/GenCheGuanLianPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		GENCHEGUANLIANSERVICE_WSDL_LOCATION = url;
	}

	public GenCheGuanLianService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public GenCheGuanLianService() {
		super(GENCHEGUANLIANSERVICE_WSDL_LOCATION, new QName(
				"http://hbase.com/", "GenCheGuanLianService"));
	}

	/**
	 * 
	 * @return returns GenCheGuanLianDelegate
	 */
	@WebEndpoint(name = "GenCheGuanLianPort")
	public GenCheGuanLianDelegate getGenCheGuanLianPort() {
		return super.getPort(new QName("http://hbase.com/",
				"GenCheGuanLianPort"), GenCheGuanLianDelegate.class);
	}

}
